sudo: false
language: python
python:
  - 2.7
  - 3.6
notifications:
  email: false
install:
  - pip install -r test_requirements.txt
stages:
  - test
  - moban

jobs:
  include:
    - stage: moban
      script:
        - moban -m upstreaming.yml
        - git diff --exit-code

stage: test

before_script:
  - git clone https://github.com/sphinx-doc/sphinx ../sphinx
  - (cd .. && ln -s sphinx/sphinx/templates/quickstart/
                    sphinx-quickstart-templates)
  - sed -i "s/{{ \(\w*\) | repr }}/'{{ \1 }}'/;s/{%- \(for\|endfor\)/{% \1/"
        ../sphinx-quickstart-templates/conf.py_t

script:
  - find templates/ -type f -name '*.jj2' -exec echo '{}' \;|sed -e "s/templates\//{%include \"/" -e "s/$/\" %}/" > test.file
  - moban -c config/data.yml -t test.file -td templates .
