sudo: false
language: python
python:
  - 2.7
  - 3.6
notifications:
  email: false
install:
  - pip install -r test_requirements.txt -r tests/requirements.txt
stages:
  - test
  - moban
  - lint

.disable_global: &disable_global
  before_install: false
  install: true
  before_script: false
  after_success: false
  after_failure: false

.lint: &lint
  <<: *disable_global
  python: 3.6
  stage: lint
  install: pip install flake8
  script: flake8

.moban: &moban
  <<: *disable_global
  python: 2.7
  stage: moban
  install: pip install moban>=0.0.4
  script:
    - make
    - make push	

jobs:
  include:
    - *moban
    - *lint
  allow_failures:
    - test

stage: test

script:
  - find templates/ -type f -name '*.jj2' -exec echo '{}' \;|sed -e "s/templates\//{%include \"/" -e "s/$/\" %}/" > test.file
  - moban -c config/data.yml -t test.file -td templates .
  - pytest
